### PR TITLE
Feature pawn move

### PR DESCRIPTION
**Pull request by taylorn16**
- Wrote Pawn#valid_move?
- Wrote Pawn#valid_vector?
- Wrote Pawn specs (8 examples)
- Wrote Game#valid_coordinate? and specs

### CODE REVIEW

**Comment by taylorn16** [comment]
@Che-cop Do you have any comments on this PR while we wait for the others to join the repo?

**Comment by Che-cop** [comment]
Everything looks good. A lot of work in there. Do you know what files are conflicting and need to be fixed before the merge?

**Comment by taylorn16** [comment]
Should only be models/game.rb

**Comment by taylorn16** [comment]
@Che-cop I refactored `Game#valid_coordinate?` in the other branch. do you want to take care of the conflict or should I?

**Comment by Che-cop** [comment]
just saw this. I can do it when I get home from work tonight or you can if you have time. Either way.

**Pull request merged**
